# Maintainer List
# -*- coding: utf-8 -*-

maintainers = {

"judd" : "judd",
"simo" : "simo",
"tobias" : "tobias",
"eric" : "eric",
"damir" : "damir",
"dale" : "dale",
"kevin" : "kevin",
"juergen" : "juergen",
"pressh" : "ronald",
"Aaron Griffin" : "aaron",
"Alexander Baldeck" : "alexander",
"Alexander Fehr" : "alexanderf",
"Allan McRae" : "allan",
"Andreas Radke" : "andyrtr",
"Dale Blount" : "dale",
"Damir Perisa" : "damir",
"Dan McGee" : "dan",
"Daniel Isenmann" : "daniel",
"Don Stewart" : "don",
"Douglas Soares de Andrade" : "douglas",
"Dusty Philips" : "dusty",
"Eduardo Romero" : "eduardo",
"Eric Belanger" : "eric",
"Firmicus" : "francois",
"François Charete" : "francois",
"Geoffroy Carrier" : "gcarrier",
"Giovanni 'voidnull' Scafora" : "giovanni",
"Giovanni Scafora" : "giovanni",
"Hugo Doria": "hdoria",
"James Rayner" : "james",
"Jason Chu" : "jason",
"Jeff Mickey" : "jeff",
"Jeff 'codemac' Mickey" : "jeff",
"Jan de Groot" : "jgc",
"Judd Vinet" : "judd",
"Juergen Hoetzel" : "juergen",
"Kevin Piche" : "kevin",
"Paul Mattal" : "paul",
"Phil Dillon-Thistleton" : "phil",
"Pierre Schmitz" : "pierre",
"Roman Kyrylych" : "roman",
"Ronald van Haren" : "ronald",
"Simo Leone" : "simo",
"Thayer Williams" : "thayer",
"Thomas Baechler" : "thomas",
"Thomas Bächler" :"thomas",
"Tobias Kieslich" : "tobias",
"Tom Killian" : "tom",
"Tobias Powalowski" : "tpowa",
"Vesa Kaihlavirta" : "vesa",
"Abhishek Dasgupta" : "abhidg",
"Anders Bergh" : "anders",
"Angel Velasquez" : "angvp",
"Angel 'angvp' Velasquez" : "angvp",
"Corrado Primier" : "bardo",
"Corrado 'bardo' Primier" : "bardo",
"Andrea Scarpino" : "bash",
"Andrea `BaSh` Scarpino" : "bash",
"Daenyth Blank" : "daenyth",
"Jaroslav Lichtblau" : "dragonlord",
"Aaron Schaefer" : "elasticdog",
"Kessia 'even' Pinheiro" : "even",
"Kessia Pinheiro" : "even",
"Evangelos Foutras" : "foutrelis",
"Dan Griffiths" : "ghost1227",
"Timm Preetz" : "gummibaerchen",
"Loui Chang" : "louipc",
"Mikko Seppäa" : "neverth",
"Imanol Celaya" : "ornitorrincos",
"Mateusz Herych" : "partition",
"Sergej Pupykin" : "sergej",
"Stefan Husmann" : "stefanhusmann",
"Jaroslaw Swierczynski" : "swiergot",
"Paulo Matias" : "thotypous"
}

