#!/bin/bash
source "/usr/share/namcap-reports/scripts/common.sh"

cd $repo_files
for i in core extra community; do
	wget -r ftp://ftp.archlinux.org/$i/os/i686/$i.db.tar.gz
	(tar tzvf ftp.archlinux.org/$i/os/i686/$i.db.tar.gz  | awk '{print $6}' | grep /$ | sed "s/\(.*\)-[0-9,a-z,A-Z,_,\.]*-[0-9]*\//\1/g") >| $repo_files/$i
done
