#!/bin/bash
source "/usr/share/namcap-reports/scripts/common.sh"

mirror_repo() {
	repo=$1
    MIRROR="http://mir.archlinux.fr/$repo/os/i686"
	echo $MIRROR
}

cd $repo_files
for i in core extra community; do
	rm "$i.db.tar.gz" > /dev/null
	wget "$(mirror_repo $i)/$i.db.tar.gz"
	(tar tzvf "$i.db.tar.gz"  | awk '{print $6}' | grep /$ | sed "s/\(.*\)-[0-9,a-z,A-Z,_,\.]*-[0-9]*\//\1/g") >| "$repo_files/$i"
done
