# Maintainer List
# -*- coding: utf-8 -*-

maintainers = {

u"judd" : "judd",
u"simo" : "simo",
u"tobias" : "tobias",
u"eric" : "eric",
u"dale" : "dale",
u"kevin" : "kevin",
u"juergen" : "juergen",
u"pressh" : "ronald",
u"Aaron Griffin" : "aaron",
u"Alexander Baldeck" : "alexander",
u"Alexander Fehr" : "alexanderf",
u"Allan McRae" : "allan",
u"Andreas Radke" : "andyrtr",
u"Dale Blount" : "dale",
u"Dan McGee" : "dan",
u"Daniel Isenmann" : "daniel",
u"Don Stewart" : "don",
u"Douglas Soares de Andrade" : "douglas",
u"Dusty Philips" : "dusty",
u"Eduardo Romero" : "eduardo",
u"Eric Belanger" : "eric",
u"Firmicus" : "francois",
u"François Charette" : "francois",
u"Geoffroy Carrier" : "gcarrier",
u"Giovanni 'voidnull' Scafora" : "giovanni",
u"Giovanni Scafora" : "giovanni",
u"Hugo Doria": "hdoria",
u"James Rayner" : "james",
u"Jason Chu" : "jason",
u"Jeff Mickey" : "jeff",
u"Jeff 'codemac' Mickey" : "jeff",
u"Jan de Groot" : "jgc",
u"Judd Vinet" : "judd",
u"Juergen Hoetzel" : "juergen",
u"Kevin Piche" : "kevin",
u"Paul Mattal" : "paul",
u"Phil Dillon-Thistleton" : "phil",
u"Pierre Schmitz" : "pierre",
u"Roman Kyrylych" : "roman",
u"Ronald van Haren" : "ronald",
u"Simo Leone" : "simo",
u"Thayer Williams" : "thayer",
u"Thomas Baechler" : "thomas",
u"Thomas Bächler" :"thomas",
u"Tobias Kieslich" : "tobias",
u"Tom Killian" : "tom",
u"Tobias Powalowski" : "tpowa",
u"Vesa Kaihlavirta" : "vesa",
u"Abhishek Dasgupta" : "abhidg",
u"Corrado Primier" : "bardo",
u"Corrado 'bardo' Primier" : "bardo",
u"Andrea Scarpino" : "bash",
u"Andrea `BaSh` Scarpino" : "bash",
u"Daenyth Blank" : "daenyth",
u"Jaroslav Lichtblau" : "dragonlord",
u"Aaron Schaefer" : "elasticdog",
u"Kessia 'even' Pinheiro" : "even",
u"Kessia Pinheiro" : "even",
u"Evangelos Foutras" : "foutrelis",
u"Dan Griffiths" : "ghost1227",
u"Timm Preetz" : "gummibaerchen",
u"Loui Chang" : "louipc",
u"Mikko Seppäla" : "neverth",
u"Imanol Celaya" : "ornitorrincos",
u"Mateusz Herych" : "partition",
u"Sergej Pupykin" : "sergej",
u"Stefan Husmann" : "stefanhusmann",
u"Jaroslaw Swierczynski" : "swiergot",
u"Paulo Matias" : "thotypous"
}

